[project]
name = "portifolio2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.4",
    "django-ckeditor>=6.7.3",
    "pillow>=11.3.0",
]
